version: "3"

services:
  app:
    image: node:16-slim
    ports:
      - 3000:3000
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace:cached

    command: sleep infinity

  redis:
    image: redis
    ports:
      - 3100:6379
